### PR TITLE
deploy storybook

### PR DESCRIPTION
**Pull request by codingknite**
Storybook Deployed to this [Link](https://61c9d1a48f648c003a72f6b8-mrapzfagia.chromatic.com/?path=/story/avatar--large-avatar)

### CODE REVIEW

**Comment by codingknite** [comment]
@martonlederer this PR has been fixed. Please use this [Link](https://www.chromatic.com/builds?appId=61c9d1a48f648c003a72f6b8) to join the storybook dashboard

The storybook is deployed at [61c9d1a48f648c003a72f6b8-olrtvfejvg.chromatic.com](https://61c9d1a48f648c003a72f6b8-olrtvfejvg.chromatic.com/)

**Comment by codingknite** [comment]
@t8 we will need to add the project token to the [github secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) of this repo.

This will allow automated deployment should any changes be made

**Comment by martonlederer** [comment]
I'm removing the Vercel deployment

**Comment by t8** [comment]
@codingknite just added you as an admin to the repo so you should be able to add the secret(s) now!

**Comment by codingknite** [comment]
thanks @t8

**Comment by codingknite** [comment]
no idea why this PR isn't merged

**Comment by martonlederer** [comment]
You can do that @codingknite

**Comment by codingknite** [comment]
Okay @martonlederer , first trying to see what's wrong with the build

**Pull request merged**
